#!/usr/bin/env bash
# This script displays listening ports along with the associated PIDs and program names

# Check if the script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

# Display active internet connections (only servers)
echo "Active Internet connections (only servers)"
ss -ltnup | awk '
BEGIN {
    print "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
}
NR > 1 {
    split($6, a, ",")
    split(a[2], b, "=")
    pid_program = b[2]
    printf "%-4s  %-5s  %-5s  %-20s  %-20s  %-12s  %s\n", $1, $2, $3, $4, $5, $6, pid_program
}'

# Display active UNIX domain sockets (only servers)
echo "Active UNIX domain sockets (only servers)"
ss -lxnp | awk '
BEGIN {
    print "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
}
NR > 1 {
    split($6, a, ",")
    split(a[2], b, "=")
    pid_program = b[2]
    printf "%-4s  %-6s %-10s %-12s %-13s %-8s  %s  %s\n", $1, $2, $3, $4, $5, $6, pid_program, $7
}'

