#!/usr/bin/env bash
# This script displays listening ports along with the PID and name of the program to which each socket belongs

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"

# Display TCP listening sockets
ss -tlnp | awk 'NR==1 || /LISTEN/ {print}'

# Display UDP listening sockets
ss -lunp | awk 'NR==1 || /UNCONN/ {print}'

echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"

# Display UNIX domain sockets
ss -lxunp | awk 'NR==1 || /LISTEN|UNCONN/ {print}'

