#!/usr/bin/env bash
# This script displays a list of currently running processes in a user-oriented format and shows the process hierarchy

# Display all processes for all users, including those which might not have a TTY, in a user-oriented format
ps aux

# Show process hierarchy
echo ""
echo "Process Hierarchy:"
pstree -p
