#!/bin/bash

# Init script to manage manage_my_process

# Check arguments
if [ $# -ne 1 ]; then
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi

# Path to manage_my_process script
MANAGE_SCRIPT="./manage_my_process"

case "$1" in
    start)
        sudo $MANAGE_SCRIPT start
        ;;
    stop)
        sudo $MANAGE_SCRIPT stop
        ;;
    restart)
        sudo $MANAGE_SCRIPT restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
