#!/bin/bash

case "$1" in
    start)
        echo "Starting manage_my_process..."
        # Check if process is already running
        if [ -f /var/run/my_process.pid ]; then
            echo "manage_my_process is already running."
            exit 1
        fi
        
        # Start manage_my_process
        (while true; do
            echo "I am alive!" >> /tmp/my_process
            sleep 2
        done) &
        
        # Record PID
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        echo "Stopping manage_my_process..."
        if [ ! -f /var/run/my_process.pid ]; then
            echo "manage_my_process is not running."
            exit 1
        fi
        
        # Stop manage_my_process
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        echo "Restarting manage_my_process..."
        if [ -f /var/run/my_process.pid ]; then
            kill "$(cat /var/run/my_process.pid)"
            rm /var/run/my_process.pid
        fi
        
        # Start manage_my_process
        (while true; do
            echo "I am alive!" >> /tmp/my_process
            sleep 2
        done) &
        
        # Record PID
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
